server:
  port: 9080
Spring:
  datasource:
    name: abms
    url: jdbc:mysql://aniikiki.cn:3306/abms
    username: root
    password: 123456
    hikari:
      connection-timeout: 60000
springfox:
  documentation:
    enabled: true
knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    username: abms
    password: qazwsx
